### PR TITLE
Doxygen fixes

### LINKED ISSUE #38: Need doxygen improvements
We need better doxygen documentation for this library.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #38 
Part of #32
Part of #42

Eliminate doxygen warnings and turned on WARN_AS_ERROR.

Also removed pfunit from github build, and turn on doc build.

### CODE REVIEW

File: src/bafrio.f90 [hunk 1]
```diff
@@ -164,45 +137,32 @@ SUBROUTINE BAFRINDEXL(LU,IB,LX,IX)
...
+!> @param IB INTEGER FORTRAN RECORD START BYTE
+!>                  (FOR THE FIRST FORTRAN RECORD, IB SHOULD BE 0)
+!> @param NB INTEGER NUMBER OF BYTES TO READ
+!> @param KA INTEGER NUMBER OF BYTES IN FORTRAN RECORD
+!>                  (IN WHICH CASE THE NEXT FORTRAN RECORD
+!>                  SHOULD HAVE A START BYTE OF IB+KA),
+!>                  OR KA=-1 FOR I/O ERROR (PROBABLE END OF FILE),
+!>                  OR KA=-2 FOR I/O ERROR (INVALID FORTRAN RECORD),
+!>                  OR KA=-3 FOR I/O ERROR (REQUEST LONGER THAN RECORD)
+!> @param A CHARACTER*1 (NB) DATA READ
```
Comment (BrianCurtis-NOAA) [inline src/bafrio.f90:161]: This is still all caps.

Comment (edwardhartnett) [reply src/bafrio.f90:161]: Will fix in a future PR. Let's get this one merged...

**Review by BrianCurtis-NOAA — APPROVED** [review]
